# Root: solo warning/error
rootLogger.level = WARN
rootLogger.appenderRef.console.ref = ConsoleAppender

# Flink e runtime: ancora più ?silenziosi?
logger.flink.name = org.apache.flink
logger.flink.level = WARN

logger.pekko.name = org.apache.pekko
logger.pekko.level = WARN

logger.akka.name = akka
logger.akka.level = WARN

logger.netty.name = io.netty
logger.netty.level = ERROR

# Tieni i tuoi log a INFO
logger.app.name = it.unicam.routinedetector
logger.app.level = INFO
logger.app.additivity = false
logger.app.appenderRef.console.ref = ConsoleAppender
